Jdp210603 23 2
piotr-grosicki/project-jdp-2106-03 pull request #35
Opened 2021-07-11 23:00 UTC by Pipen27

2021-07-12 13:26 UTC, C0nn0rJ0hn requested changes

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +    public void createOrderBasedOnCart (final Long cartId, final Long orderId) {
ta metoda wydaje mi się że jest źle bo ma być utworzone zamówienie na podstawie koszyka a tutaj w metodzie szukasz już zamówienia które istnieje

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        Cart activeCart = cartById.get();
ja osobiscie bym się tutaj posługiwał na cart, czyli activeCart.getProducts().add() i to samo przy deleteProduct ale to co jest tez jest ok :)

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +    public List<Product> addProductToCart(final Long productId, final Long cartId) {
zastanawiaja mnie te metody addProduct i deleteProduct - czy nie lepiej zwrocic tutaj caly obiektCart? widac wtedy idCart i liste produktow wiec widac tez czy produkt sie dodal czy też nie. Do przemyslenia :)

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private long productId;
czemu dodałeś to? bo nie rozumiem za bardzo

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/dto/CartDto.java
> +    private List<Product> products = new ArrayList<>();
lista powinna być po id produktach - tak mówił Piotr, żeby uniknąc zapętleń

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/dto/CartDto.java
> +    private long productId;
nie wiem po co to jest productId?

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +                productRepository.findById(cartDto.getProductId())
po co w konstruktorze jest id produktu jednego?

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
> +                cart.getProductId()
to samo

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @GetMapping(value = "cartContains")
zastanowiłbym się czy nie lepiej zwrocic caly obiekt CartDto?

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> addProductToCart(@RequestParam Long cartId,
CartDto?

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> removeProductFromCart(@RequestParam Long cartId,
CartDto?

2021-07-12 13:26 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createOrder(@RequestParam Long cartId,
zamowienie ma byc tworzone na podstawie koszyka więc nie mozesz w argumentach metody podawac juz istniejacego zamowienia bo to wlasnie metoda ma stworzyc zamowienie

2021-07-14 11:08 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createCart(@RequestBody CartDto cartDto){
Poprawione, body metody createCart:

Cart cart = cartService.saveCart(cartMapper.mapToCart(cartDto));
        return cartMapper.mapToCartDto(cart);

2021-07-14 11:27 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +    public void createOrderBasedOnCart (final Long cartId, final Long orderId) {
Masz rację, bez sensu w takiej postaci, poprawione

2021-07-14 11:29 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        Cart activeCart = cartById.get();
Zostawiam zatem w takiej postaci na razie

2021-07-14 11:37 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private long productId;
public Product mapToProduct(final ProductDto productDto) {

        return new Product(
                productDto.getId(),
                productDto.getName(),
                productDto.getShortDesc(),
                productDto.getLongDesc(),
                productDto.getProductPrice(),
                productDto.getQuantityOnStore(),
                productDto.getProductCondition(),
                productDto.getProductWeight(),
                productDto.isStillOnSale(),
                groupRepository.findById(productDto.getGroupId()).orElse(null)
        );

Sugerowałem się Twoim mapperem i powiązaniem product z group, tak samo chciałem to zrobić dla cart i product, ale jeżeli jest to zbędnę to usunę to pole productId

2021-07-14 11:42 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @GetMapping(value = "cartContains")
poprawione

2021-07-14 11:44 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void createOrder(@RequestParam Long cartId,
jak wyżej odnośnie 
public Order createOrderBasedOnCart (final Long cartId) w CartService;

poprawione

2021-07-14 12:09 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/domain/dto/CartDto.java
> +    private List<Product> products = new ArrayList<>();
nie za bardzo rozumiem, czyli jako argument lista products powinna przyjmować co?

2021-07-14 12:19 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> addProductToCart(@RequestParam Long cartId,
zmieniłem

2021-07-14 12:19 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public List<ProductDto> removeProductFromCart(@RequestParam Long cartId,
zmieniłem

2021-07-14 12:20 UTC, Pipen27 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +    public List<Product> addProductToCart(final Long productId, final Long cartId) {
Przemyślałem i zmieniłem :)

2021-07-14 14:23 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private long productId;
no bo product ma relacje one to many z group, cart ma relacje many to many z product wiec ten productId jest zbedny bo relacja jest opisana przez liste.

2021-07-14 14:23 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    public long getProductId() {
zbedny getter i setter dla ProductId

2021-07-14 14:23 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/dto/CartDto.java
> +    private List<Product> products = new ArrayList<>();
wyjasnione na czacie na Skype ale konkluzja jest taka ze powinno byc: List<Long>productsId = new ArrayList<>();

2021-07-14 14:23 UTC, C0nn0rJ0hn commented on src/main/java/com/kodilla/ecommercee/domain/dto/CartDto.java
> +    private long productId;
usun ten productId

2021-07-14 21:40 UTC, Pipen27 commented
Wysłałem kolejnego pull requesta, ponieważ namieszałem coś na tej gałęzi i łatwiej mi było stworzyć nowego brancha, bo nie mogłem sobie poradzić w inny sposób, dlatego zamykam tego pull requesta

2021-07-14 21:40 UTC, closed without merging