Jdp210603 5
piotr-grosicki/project-jdp-2106-03 pull request #7
Opened 2021-06-27 12:21 UTC by Pipen27

2021-06-27 14:22 UTC, piotr-grosicki requested changes
konflikty do poprawienia: https://www.jetbrains.com/help/idea/resolve-conflicts.html

2021-06-27 14:22 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/kodilla_project?serverTimezone=Europe/Warsaw&useSSL=False
problemy rozwiazujemy, nie komentujemy ;)

2021-06-27 20:36 UTC, Pipen27 commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/kodilla_project?serverTimezone=Europe/Warsaw&useSSL=False
Jasne, próbowałem namierzyć wczoraj co powodowało mój błąd i zapomniałem odkomentować :)

2021-06-28 06:47 UTC, piotr-grosicki requested changes

2021-06-28 06:47 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/exception/UserNotFoundException.java
> +    public String getMessage() {
override tej metody nie ma sensu, logika jest dokladnie taka sama jakby tego override nie bylo

2021-06-29 18:36 UTC, piotr-grosicki requested changes

2021-06-29 18:36 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/exception/UserNotFoundException.java
> +    public String getMessage() {
usuniecie override nic nie zmienia, tej metody tutaj nie powinno byc

2021-06-29 19:20 UTC, Pipen27 commented
Usunięte

2021-06-29 19:53 UTC, piotr-grosicki approved these changes

2021-06-29 19:53 UTC, merged